spring.application.name=bknd-expenses

server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gastos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Mostrar errores durante desarrollo
server.error.include-stacktrace=always
server.error.include-message=always

# JWT
# Debe ser exactamente igual al secret del microservicio de usuarios y categorías
jwt.secret=clave-super-secreta-para-testeo-1234567890
jwt.expiration=86400000

# Swagger/SpringDoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true